# Generated by Django 3.2.13 on 2022-07-03 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('PaperID', models.IntegerField(primary_key=True, serialize=False)),
                ('Active', models.BooleanField(default=None, null=True)),
                ('FilenameOriginal', models.CharField(blank=True, max_length=100, null=True)),
                ('Filename', models.CharField(blank=True, max_length=100, null=True)),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Certification', models.CharField(blank=True, max_length=3, null=True)),
                ('NotesToReviewers', models.CharField(blank=True, max_length=255, null=True)),
                ('AnalysisOfAlgorithms', models.BooleanField(default=None, null=True)),
                ('Applications', models.BooleanField(default=None, null=True)),
                ('Architecture', models.BooleanField(default=None, null=True)),
                ('ArtificialIntelligence', models.BooleanField(default=None, null=True)),
                ('ComputerEngineering', models.BooleanField(default=None, null=True)),
                ('Curriculum', models.BooleanField(default=None, null=True)),
                ('DataStructures', models.BooleanField(default=None, null=True)),
                ('Databases', models.BooleanField(default=None, null=True)),
                ('DistanceLearning', models.BooleanField(default=None, null=True)),
                ('DistributedSystems', models.BooleanField(default=None, null=True)),
                ('EthicalSocietalIssues', models.BooleanField(default=None, null=True)),
                ('FirstYearComputing', models.BooleanField(default=None, null=True)),
                ('GenderIssues', models.BooleanField(default=None, null=True)),
                ('GrantWriting', models.BooleanField(default=None, null=True)),
                ('GraphicsImageProcessing', models.BooleanField(default=None, null=True)),
                ('HumanComputerInteraction', models.BooleanField(default=None, null=True)),
                ('LaboratoryEnvironments', models.BooleanField(default=None, null=True)),
                ('Literacy', models.BooleanField(default=None, null=True)),
                ('MathematicsInComputing', models.BooleanField(default=None, null=True)),
                ('Multimedia', models.BooleanField(default=None, null=True)),
                ('NetworkingDataCommunications', models.BooleanField(default=None, null=True)),
                ('NonMajorCourses', models.BooleanField(default=None, null=True)),
                ('ObjectOrientedIssues', models.BooleanField(default=None, null=True)),
                ('OperatingSystems', models.BooleanField(default=None, null=True)),
                ('ParallelProcessing', models.BooleanField(default=None, null=True)),
                ('Pedagogy', models.BooleanField(default=None, null=True)),
                ('ProgrammingLanguages', models.BooleanField(default=None, null=True)),
                ('Research', models.BooleanField(default=None, null=True)),
                ('Security', models.BooleanField(default=None, null=True)),
                ('SoftwareEngineering', models.BooleanField(default=None, null=True)),
                ('SystemsAnalysisAndDesign', models.BooleanField(default=None, null=True)),
                ('UsingTechnologyInTheClassroom', models.BooleanField(default=None, null=True)),
                ('WebAndInternetProgramming', models.BooleanField(default=None, null=True)),
                ('Other', models.BooleanField(default=None, null=True)),
                ('OtherDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('AuthorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.IntegerField(primary_key=True, serialize=False)),
                ('AppropriatenessOfTopic', models.DecimalField(decimal_places=2, max_digits=3)),
                ('TimelinessOfTopic', models.DecimalField(decimal_places=2, max_digits=3)),
                ('SupportiveEvidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('TechnicalQuality', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ScopeOfCoverage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('CitationOfPreviousWork', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Originality', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ContentComments', models.DecimalField(decimal_places=2, max_digits=3)),
                ('OrganizationOfPapers', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ClarityOfMainMessage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Mechanics', models.DecimalField(decimal_places=2, max_digits=3)),
                ('WrittenDocumentComments', models.CharField(blank=True, max_length=255, null=True)),
                ('SuitabilityForPresentation', models.DecimalField(decimal_places=2, max_digits=3)),
                ('PotentialInterestInTopic', models.DecimalField(decimal_places=2, max_digits=3)),
                ('PotentialForOralPresentationComments', models.CharField(blank=True, max_length=255, null=True)),
                ('OverallRating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('OverallRatingComments', models.CharField(blank=True, max_length=255, null=True)),
                ('ComfortLevelTopic', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ComfortLevelAcceptability', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Complete', models.BooleanField(default=None, null=True)),
                ('PaperID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paper')),
                ('ReviewerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
