# Generated by Django 3.2.13 on 2022-07-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220706_0155'),
        ('home', '0003_auto_20220706_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='AuthorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usercat'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ReviewerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usercat'),
        ),
    ]
