# Generated by Django 3.2.13 on 2022-07-07 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220706_0155'),
        ('home', '0005_auto_20220706_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='Active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='AuthorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.author'),
        ),
    ]
