# Generated by Django 3.2.13 on 2022-07-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220707_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='PaperID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
