# Generated by Django 3.2.13 on 2022-07-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_paper_paperid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='ReviewID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
