# Generated by Django 3.2.13 on 2022-07-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220707_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Complete',
            field=models.BooleanField(blank=True, choices=[(True, 'Complete'), (False, 'Incomplete'), (None, 'Undetermined')], default=False, null=True),
        ),
    ]
