# Generated by Django 3.2.13 on 2022-07-03 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, choices=[('Reviewer', 'Reviewer'), ('Author', 'Author'), ('Admin', 'Admin')], max_length=20, null=True)),
                ('Active', models.BooleanField(default=None, null=True)),
                ('MiddleInitial', models.CharField(blank=True, max_length=1, null=True)),
                ('Affiliation', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=2, null=True)),
                ('ZipCode', models.CharField(blank=True, max_length=10, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('AnalysisOfAlgorithms', models.BooleanField(default=None, null=True)),
                ('Applications', models.BooleanField(default=None, null=True)),
                ('Architecture', models.BooleanField(default=None, null=True)),
                ('ArtificialIntelligence', models.BooleanField(default=None, null=True)),
                ('ComputerEngineering', models.BooleanField(default=None, null=True)),
                ('Curriculum', models.BooleanField(default=None, null=True)),
                ('DataStructures', models.BooleanField(default=None, null=True)),
                ('Databases', models.BooleanField(default=None, null=True)),
                ('DistanceLearning', models.BooleanField(default=None, null=True)),
                ('DistributedSystems', models.BooleanField(default=None, null=True)),
                ('EthicalSocietalIssues', models.BooleanField(default=None, null=True)),
                ('FirstYearComputing', models.BooleanField(default=None, null=True)),
                ('GenderIssues', models.BooleanField(default=None, null=True)),
                ('GrantWriting', models.BooleanField(default=None, null=True)),
                ('GraphicsImageProcessing', models.BooleanField(default=None, null=True)),
                ('HumanComputerInteraction', models.BooleanField(default=None, null=True)),
                ('LaboratoryEnvironments', models.BooleanField(default=None, null=True)),
                ('Literacy', models.BooleanField(default=None, null=True)),
                ('MathematicsInComputing', models.BooleanField(default=None, null=True)),
                ('Multimedia', models.BooleanField(default=None, null=True)),
                ('NetworkingDataCommunications', models.BooleanField(default=None, null=True)),
                ('NonMajorCourses', models.BooleanField(default=None, null=True)),
                ('ObjectOrientedIssues', models.BooleanField(default=None, null=True)),
                ('OperatingSystems', models.BooleanField(default=None, null=True)),
                ('ParallelProcessing', models.BooleanField(default=None, null=True)),
                ('Pedagogy', models.BooleanField(default=None, null=True)),
                ('ProgrammingLanguages', models.BooleanField(default=None, null=True)),
                ('Research', models.BooleanField(default=None, null=True)),
                ('Security', models.BooleanField(default=None, null=True)),
                ('SoftwareEngineering', models.BooleanField(default=None, null=True)),
                ('SystemsAnalysisAndDesign', models.BooleanField(default=None, null=True)),
                ('UsingTechnologyInTheClassroom', models.BooleanField(default=None, null=True)),
                ('WebAndInternetProgramming', models.BooleanField(default=None, null=True)),
                ('Other', models.BooleanField(default=None, null=True)),
                ('OtherDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('ReviewsAcknowledged', models.BooleanField(default=None, null=True)),
                ('ReviewerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, choices=[('Reviewer', 'Reviewer'), ('Author', 'Author'), ('Admin', 'Admin')], max_length=20, null=True)),
                ('MiddleInitial', models.CharField(blank=True, max_length=1, null=True)),
                ('Affiliation', models.CharField(blank=True, max_length=50, null=True)),
                ('Department', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=2, null=True)),
                ('ZipCode', models.CharField(blank=True, max_length=10, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('AuthorID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
