# Generated by Django 3.2.13 on 2022-07-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220706_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='Active',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive'), (None, 'Undetermined')], default=True, null=True),
        ),
    ]
